### ISSUE TITLE
Explainer can go in README

### ISSUE THREAD

**Issue by npm1** [oyiptong/compute-pressure#1]
I think it's fine to move the explainer to the README, so that it's visible on https://github.com/oyiptong/compute-pressure Alternatively, link the explainer from the README so that people don't have to dig through file names to find the explainer.

**Comment by pwnall** [comment]
Thank you for the suggestion!

Moved the explainer into the README in https://github.com/oyiptong/compute-pressure/commit/9316668a5819dc1ec56e2f880e35595d5fbf1892
